version: '3'

includes:
  selftest:
    taskfile: ./task/selftest/Taskfile.yml
    dir: .

tasks:
  # ==========================================================================
  # 测试入口
  # ==========================================================================
  test:
    desc: "运行所有自测试"
    cmds:
      - task: selftest:default

  test:quick:
    desc: "快速测试"
    cmds:
      - task: selftest:quick

  # ==========================================================================
  # 示例任务 (用于测试 ez 命令)
  # ==========================================================================
  hello:
    desc: "Say hello"
    cmds:
      - cmd: echo "Hello, {{.EZ_NAME}}!"
    ez-params:
      - name: "name"
        type: "input"
        default: "World"
        help: "Your name"

  build:
    desc: "Build project"
    cmds:
      - cmd: echo "Building for {{.EZ_ARCH}}"
    ez-params:
      - name: "arch"
        type: "select"
        options: ["x86_64", "aarch64", "riscv64"]
        default: "x86_64"
        help: "Target architecture"

  clean:
    desc: "Clean artifacts"
    cmds:
      - cmd: echo "Cleaning..."

  # ==========================================================================
  # 动态选项示例 (query.command)
  # ==========================================================================
  git-checkout:
    desc: "切换 Git 分支"
    cmds:
      - cmd: echo "Switching to branch {{.EZ_BRANCH}}"
    ez-params:
      - name: "branch"
        type: "select"
        query:
          command: "git branch --format='%(refname:short)'"
        help: "选择分支"

  fetch-ip:
    desc: "获取 IP 信息 (query.url 示例)"
    cmds:
      - cmd: echo "Selected format {{.EZ_FORMAT}}"
    ez-params:
      - name: "format"
        type: "select"
        query:
          url: "https://httpbin.org/get"
          jq: ".headers | keys"
        default: "Host"
        help: "选择 HTTP header"

  # ==========================================================================
  # 复杂参数示例 (多行帮助、多参数)
  # ==========================================================================
  deploy:
    desc: "部署应用到服务器"
    cmds:
      - cmd: 'echo "Deploying {{.EZ_APP}} to {{.EZ_ENV}} ({{.EZ_REGION}})"'
      - cmd: 'echo "Replicas = {{.EZ_REPLICAS}}"'
    ez-params:
      - name: "app"
        type: "select"
        options: ["frontend", "backend", "api-gateway"]
        default: "frontend"
        help: |
          选择要部署的应用
          - frontend: React 前端应用
          - backend: Node.js 后端服务
          - api-gateway: API 网关

      - name: "env"
        type: "select"
        options: ["dev", "staging", "prod"]
        default: "dev"
        help: |
          目标环境
          ⚠️ prod 环境需要审批

      - name: "region"
        type: "select"
        options: ["cn-north", "cn-east", "us-west"]
        default: "cn-north"
        help: "部署区域"

      - name: "replicas"
        type: "input"
        default: "2"
        help: "副本数量 (1-10)"

  # ==========================================================================
  # ez-hooks 示例
  # ==========================================================================
  build-with-hooks:
    desc: "带钩子的构建任务"
    cmds:
      - cmd: 'echo "Building project..."'
      - cmd: 'echo "Build completed!"'
    ez-hooks:
      pre_run:
        - name: "check-env"
          script: 'echo "  Checking environment..."'
      post_run:
        - name: "notify-success"
          script: 'echo "  Build succeeded! Task: $EZ_TASK_NAME"'
        - name: "cleanup"
          script: 'echo "  Cleaning temp files..."'

  fail-with-hooks:
    desc: "测试 on_error 钩子"
    cmds:
      - cmd: 'echo "Starting..."'
      - cmd: 'exit 1'
    ez-hooks:
      on_error:
        - name: "notify-failure"
          script: 'echo "  Task failed with exit code: $EZ_TASK_EXIT_CODE"'

  # ==========================================================================
  # Linux 内核模拟测试任务
  # ==========================================================================
  kernel-config:
    desc: "配置内核选项"
    cmds:
      - cmd: 'echo "[config] ARCH={{.EZ_ARCH}} CONFIG={{.EZ_CONFIG}}"'
      - cmd: 'echo "[config] 生成 .config 文件..."'
    ez-params:
      - name: "arch"
        type: "select"
        options: ["x86_64", "arm64", "riscv"]
        default: "x86_64"
        help: "目标架构"
      - name: "config"
        type: "select"
        options: ["defconfig", "allmodconfig", "tinyconfig"]
        default: "defconfig"
        help: "配置模板"

  kernel-build:
    desc: "编译内核"
    cmds:
      - cmd: 'echo "[build] ARCH={{.EZ_ARCH}} JOBS={{.EZ_JOBS}}"'
      - cmd: 'echo "[build] 编译中... (模拟)"'
      - cmd: 'sleep 1'
      - cmd: 'echo "[build] 生成 vmlinux bzImage"'
    ez-params:
      - name: "arch"
        type: "select"
        options: ["x86_64", "arm64", "riscv"]
        default: "x86_64"
        help: "目标架构"
      - name: "jobs"
        type: "input"
        default: "4"
        help: "并行编译数 (-j)"

  kernel-test:
    desc: "运行内核测试"
    cmds:
      - cmd: 'echo "[test] SUITE={{.EZ_SUITE}} on {{.EZ_MACHINE}}"'
      - cmd: 'echo "[test] 运行测试套件..."'
      - cmd: 'sleep 1'
      - cmd: 'echo "[test] PASS: 42 FAIL: 0"'
    ez-params:
      - name: "suite"
        type: "select"
        options: ["unit", "smoke", "full", "stress"]
        default: "smoke"
        help: "测试套件"
      - name: "machine"
        type: "select"
        options: ["qemu", "hw-x86", "hw-arm", "hw-riscv"]
        default: "qemu"
        help: "测试机器"

  kernel-package:
    desc: "打包内核"
    cmds:
      - cmd: 'echo "[package] FORMAT={{.EZ_FORMAT}} VERSION={{.EZ_VERSION}}"'
      - cmd: 'echo "[package] 生成安装包..."'
    ez-params:
      - name: "format"
        type: "select"
        options: ["deb", "rpm", "tar.gz"]
        default: "tar.gz"
        help: "包格式"
      - name: "version"
        type: "input"
        default: "6.8.0-test"
        help: "版本号"

  kernel-deploy:
    desc: "部署内核到测试机"
    cmds:
      - cmd: 'echo "[deploy] TARGET={{.EZ_TARGET}} METHOD={{.EZ_METHOD}}"'
      - cmd: 'echo "[deploy] 部署中..."'
    ez-params:
      - name: "target"
        type: "select"
        options: ["local", "vm-pool", "hw-lab"]
        default: "local"
        help: "部署目标"
      - name: "method"
        type: "select"
        options: ["kexec", "reboot", "pxe"]
        default: "kexec"
        help: "部署方式"

  kernel-report:
    desc: "生成测试报告"
    cmds:
      - cmd: 'echo "[report] 汇总测试结果..."'
      - cmd: 'echo "[report] 生成 report.html"'

  # ==========================================================================
  # 远程执行任务 (模拟)
  # ==========================================================================
  remote-copy:
    desc: "复制文件到远程主机"
    cmds:
      - cmd: 'echo "[remote-copy] HOST={{.EZ_HOST}} FILE={{.EZ_FILE}}"'
      - cmd: 'echo "[remote-copy] scp {{.EZ_FILE}} {{.EZ_HOST}}:/tmp/"'
      - cmd: 'echo "[remote-copy] 传输完成"'
    ez-params:
      - name: "host"
        type: "input"
        default: "localhost"
        help: "远程主机"
      - name: "file"
        type: "input"
        default: "vmlinux"
        help: "要传输的文件"

  remote-exec:
    desc: "在远程主机执行命令"
    cmds:
      - cmd: 'echo "[remote-exec] HOST={{.EZ_HOST}}"'
      - cmd: 'echo "[remote-exec] CMD={{.EZ_CMD}}"'
      - cmd: 'echo "[remote-exec] ssh {{.EZ_HOST}} \"{{.EZ_CMD}}\""'
      - cmd: 'echo "[remote-exec] 执行完成"'
    ez-params:
      - name: "host"
        type: "input"
        default: "localhost"
        help: "远程主机"
      - name: "cmd"
        type: "input"
        default: "uname -a"
        help: "要执行的命令"

  remote-status:
    desc: "检查远程主机状态"
    cmds:
      - cmd: 'echo "[remote-status] 检查 {{.EZ_HOST}} 状态..."'
      - cmd: 'echo "[remote-status] 主机在线，负载正常"'
    ez-params:
      - name: "host"
        type: "select"
        query:
          command: "echo -e 'node-1\nnode-2\nnode-3\ntest-server-1'"
        help: "选择远程主机"

  # ==========================================================================
  # 结果归档和统计任务
  # ==========================================================================
  result-archive:
    desc: "归档测试结果"
    cmds:
      - cmd: 'mkdir -p .ez-results/{{.EZ_RUN_ID}}'
      - cmd: 'echo "{\"run_id\": \"{{.EZ_RUN_ID}}\", \"status\": \"{{.EZ_STATUS}}\", \"timestamp\": \"$(date -Iseconds)\"}" > .ez-results/{{.EZ_RUN_ID}}/meta.json'
      - cmd: 'echo "[archive] 结果已归档到 .ez-results/{{.EZ_RUN_ID}}/"'
    ez-params:
      - name: "run_id"
        type: "input"
        default: "run-$(date +%Y%m%d-%H%M%S)"
        help: "运行 ID"
      - name: "status"
        type: "select"
        options: ["pass", "fail", "skip"]
        default: "pass"
        help: "运行状态"

  result-stats:
    desc: "显示测试统计"
    cmds:
      - cmd: 'echo "=== 测试结果统计 ==="'
      - cmd: 'echo "总运行数: $(ls -1d .ez-results/*/ 2>/dev/null | wc -l || echo 0)"'
      - cmd: 'echo "通过: $(grep -l "pass" .ez-results/*/meta.json 2>/dev/null | wc -l || echo 0)"'
      - cmd: 'echo "失败: $(grep -l "fail" .ez-results/*/meta.json 2>/dev/null | wc -l || echo 0)"'

  result-clean:
    desc: "清理旧的测试结果"
    cmds:
      - cmd: 'echo "[clean] 保留最近 {{.EZ_KEEP}} 次运行结果"'
      - cmd: 'ls -1dt .ez-results/*/ 2>/dev/null | tail -n +$(({{.EZ_KEEP}}+1)) | xargs -r rm -rf'
      - cmd: 'echo "[clean] 清理完成"'
    ez-params:
      - name: "keep"
        type: "input"
        default: "10"
        help: "保留的运行数量"
