version: '3'

includes:
  selftest:
    taskfile: ./task/selftest/Taskfile.yml
    dir: .

tasks:
  # ==========================================================================
  # 测试入口
  # ==========================================================================
  test:
    desc: "运行所有自测试"
    cmds:
      - task: selftest:default

  test:quick:
    desc: "快速测试"
    cmds:
      - task: selftest:quick

  # ==========================================================================
  # 示例任务 (用于测试 ez 命令)
  # ==========================================================================
  hello:
    desc: "Say hello"
    cmds:
      - cmd: echo "Hello, {{.EZ_NAME}}!"
    ez-params:
      - name: "name"
        type: "input"
        default: "World"
        help: "Your name"

  build:
    desc: "Build project"
    cmds:
      - cmd: echo "Building for {{.EZ_ARCH}}"
    ez-params:
      - name: "arch"
        type: "select"
        options: ["x86_64", "aarch64", "riscv64"]
        default: "x86_64"
        help: "Target architecture"

  clean:
    desc: "Clean artifacts"
    cmds:
      - cmd: echo "Cleaning..."

  # ==========================================================================
  # 动态选项示例 (query.command)
  # ==========================================================================
  git-checkout:
    desc: "切换 Git 分支"
    cmds:
      - cmd: echo "Switching to branch {{.EZ_BRANCH}}"
    ez-params:
      - name: "branch"
        type: "select"
        query:
          command: "git branch --format='%(refname:short)'"
        help: "选择分支"
